import type { Metadata } from "next";
import "@/scss/globals.scss";

export const metadata: Metadata = {
  title: "Documents",
  description: "Generated by create next app",
};

export default function DocumentsPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children} </div>;
}
