import type { Metadata } from "next";
import "../scss/globals.scss";
import { Roboto } from "next/font/google";
import { TheHeader } from "@/components/HeaderComponent/TheHeader";
import { TheFooter } from "@/components/FooterComponent/TheFooter";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "400", "700"] });
export const metadata: Metadata = {
  title: "Главная",
  description: "Generated by create next app",
  icons: "logo.svg",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="wrapper">
          <TheHeader />
          <main className="main">{children}</main>
          <TheFooter />
        </div>
      </body>
    </html>
  );
}
