import type { Metadata } from "next";
import "@/scss/globals.scss";

// export const metadata: Metadata = {
//   title: "Kompaniya haqida",
//   description: "Generated by create next app",
// };
export const generateMetadata = async ({
  params,
}: {
  params: { locale: string };
}) => {
  const { AboutPage } = await import(`@/messages/${params.locale}.json`);
  return {
    title: AboutPage.heroTitle1,
    description: AboutPage.content,
  };
};
export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
