import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Procurements",
  description: "Generated by create next app",
};

export default function TendersPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
