import type { Metadata } from "next";
import "../../scss/globals.scss";

export const metadata: Metadata = {
  title: "Новости",
  description: "Generated by create next app",
};

export default function NewsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
