import type { Metadata } from "next";
import "@/scss/globals.scss";

export const metadata: Metadata = {
  title: "Branches",
  description: "Generated by create next app",
};

export default function CeoLayout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
